# Лабораторна робота 5

In [3]:
N = ord("K") % 15 + 1
print(f"{N}")

1


### Завдання 1

1. Виконати набір вправ. Всі завдання виконати 2 способами:
   а) з використанням універсальних функцій бібліотеки NumPy [4].
   b) за допомогою ітеративних конструкцій (з використанням циклів,
спискових включень тощо).
    с) для обох випадків підрахувати час виконання скрипту та зробити
висновок.

#### Вправа 1. 
Вводиться число n. Вивести масив разміра nхn, в якому по
діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [19]:
import numpy as np
import time

def task1_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.diag(np.arange(1, n + 1))
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task1_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]
    end = time.time()
    for row in arr: print(row)
    print("Час виконання:", end - start)

In [20]:
task1_numpy()
task1_iter()

Введіть n:  5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Час виконання (NumPy): 8.916854858398438e-05


Введіть n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
Час виконання: 1.0967254638671875e-05


#### Вправа 6. 
З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.

In [34]:
def task6_numpy():
    arr = np.array(list(map(int, input("Введіть масив: ").split())))
    start = time.time()
    arr[arr != 0] = -1
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task6_iter():
    arr = list(map(int, input("Введіть масив: ").split()))
    start = time.time()
    result = [-1 if x != 0 else 0 for x in arr]
    end = time.time()
    print(result)
    print("Час виконання:", end - start)

In [32]:
task6_numpy()
task6_iter()

Введіть масив:  3 4 0 9 7 0 6 0 4 0 3


[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Час виконання (NumPy): 3.981590270996094e-05


Введіть масив:  3 4 0 9 7 0 6 0 4 0 3


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]
Час виконання: 4.76837158203125e-06


#### Вправа 7. 
З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [35]:
def task7_numpy():
    arr = np.array(list(map(int, input("Введіть масив: ").split())))
    start = time.time()
    arr[arr == 0] = -1
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task7_iter():
    arr = list(map(int, input("Введіть масив: ").split()))
    start = time.time()
    result = [-1 if x == 0 else x for x in arr]
    end = time.time()
    print(result)
    print("Час виконання:", end - start)

In [36]:
task7_numpy()
task7_iter()

Введіть масив:  3 4 0 6 5 0 3 0 4


[ 3  4 -1  6  5 -1  3 -1  4]
Час виконання (NumPy): 0.0001518726348876953


Введіть масив:  3 4 0 6 5 0 3 0 4


[3, 4, -1, 6, 5, -1, 3, -1, 4]
Час виконання: 5.0067901611328125e-06


#### Вправа 9. 
Вводиться число n. Створити масив значень від n до 0.

In [37]:
def task9_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.arange(n, -1, -1)
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task9_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = [i for i in range(n, -1, -1)]
    end = time.time()
    print(arr)
    print("Час виконання:", end - start)

In [38]:
task9_numpy()
task9_iter()

Введіть n:  10


[10  9  8  7  6  5  4  3  2  1  0]
Час виконання (NumPy): 0.0002090930938720703


Введіть n:  10


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Час виконання: 2.5033950805664062e-05


#### Вправа 10. 
Вводиться числа n i m. Створити масив випадкових значень n на m
і обчислити мінімальне, максимальне значення, середнє та середньо
квадратичне відхилення, округлене до 3 знаків після коми

In [44]:
import random

def task10_numpy():
    n, m = map(int, input("Введіть n і m: ").split())
    start = time.time()
    arr = np.random.rand(n, m)
    print("Мінімум:", round(np.min(arr), 3))
    print("Максимум:", round(np.max(arr), 3))
    print("Середнє:", round(np.mean(arr), 3))
    print("Дисперсія:", round(np.var(arr), 3))
    end = time.time()
    print("Час виконання (NumPy):", end - start)

def task10_iter():
    n, m = map(int, input("Введіть n і m: ").split())
    start = time.time()
    arr = [[random.random() for i in range(m)] for i in range(n)]
    arr2 = [x for row in arr for x in row]
    mean = sum(arr2) / len(arr2)
    variance = sum((x - mean)**2 for x in arr2) / len(arr2)
    print("Мінімум:", round(min(arr2), 3))
    print("Максимум:", round(max(arr2), 3))
    print("Середнє:", round(mean, 3))
    print("Дисперсія:", round(variance, 3))
    end = time.time()
    print("Час виконання:", end - start)

In [45]:
task10_numpy()
task10_iter()

Введіть n і m:  4 5


Мінімум: 0.103
Максимум: 0.997
Середнє: 0.513
Дисперсія: 0.083
Час виконання (NumPy): 0.0005519390106201172


Введіть n і m:  4 5


Мінімум: 0.052
Максимум: 0.896
Середнє: 0.4
Дисперсія: 0.05
Час виконання: 0.00032806396484375


#### Вправа 11. 
Створити масив одиниць розміром n х n та додати до нього
«рамку», сформовану з 0.

In [47]:
def task11_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.ones((n, n), dtype=int)
    arr = np.pad(arr, 1, constant_values=0)
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task11_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = [[1]*n for i in range(n)]
    arr = [[0]*(n+2)] + [[0]+r+[0] for r in arr] + [[0]*(n+2)]
    end = time.time()
    for r in arr: print(r)
    print("Час виконання:", end - start)

In [49]:
task11_numpy()
task11_iter()

Введіть n:  4


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
Час виконання (NumPy): 0.0002372264862060547


Введіть n:  4


[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
Час виконання: 1.3113021850585938e-05


#### Вправа 15. 
Заповнити парні стовбчики матриці розміром n х n одиницями, а
непарні – нулями.

In [50]:
def task15_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.zeros((n, n), dtype=int)
    arr[:, 1::2] = 1
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task15_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = [[1 if j % 2 else 0 for j in range(n)] for i in range(n)]
    end = time.time()
    for r in arr: print(r)
    print("Час виконання:", end - start)

In [51]:
task15_numpy()
task15_iter()

Введіть n:  5


[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Час виконання (NumPy): 0.0002510547637939453


Введіть n:  5


[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
Час виконання: 3.0994415283203125e-05


#### Вправа 17. 
Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх
значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [52]:
def task17_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.arange(n + 1)
    arr[(arr < n/2) | (arr > (3*n)/4)] *= -1
    end = time.time()
    print(arr)
    print("Час виконання (NumPy):", end - start)

def task17_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = []
    for i in range(n + 1):
        if i < n/2 or i > (3*n)/4:
            arr.append(-i)
        else:
            arr.append(i)
    end = time.time()
    print(arr)
    print("Час виконання:", end - start)

In [53]:
task17_numpy()
task17_iter()

Введіть n:  10


[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
Час виконання (NumPy): 0.0043599605560302734


Введіть n:  10


[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
Час виконання: 1.2874603271484375e-05


#### Вправа 18. 
Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99.
Визначити кількість унікальних чисел в послідовності.

In [55]:
def task18_numpy():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = np.random.randint(0, 100, n)
    unique = len(np.unique(arr))
    end = time.time()
    print("Масив:", arr)
    print("Унікальних чисел:", unique)
    print("Час виконання (NumPy):", end - start)

def task18_iter():
    n = int(input("Введіть n: "))
    start = time.time()
    arr = [random.randint(0, 99) for i in range(n)]
    unique = len(set(arr))
    end = time.time()
    print("Масив:", arr)
    print("Унікальних чисел:", unique)
    print("Час виконання:", end - start)

In [56]:
task18_numpy()
task18_iter()

Введіть n:  30


Масив: [75 42 61 90 29 33 36 54 36 67 68 35 57 12 64 65 51 15 92 42 68 82 18 58
 27 76 94 76 97 74]
Унікальних чисел: 26
Час виконання (NumPy): 0.005986928939819336


Введіть n:  30


Масив: [68, 19, 70, 87, 84, 37, 60, 31, 74, 5, 97, 0, 58, 22, 53, 39, 53, 83, 0, 45, 67, 13, 9, 96, 20, 72, 82, 45, 88, 12]
Унікальних чисел: 27
Час виконання: 0.0015621185302734375


### Завдання 2 

2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за
допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose()

$$
\begin{cases}
x_1 + x_2 + 2x_3 + 3x_4 = 1 \\
3x_1 - x_2 - x_3 - 2x_4 = -4 \\
2x_1 - 3x_2 - x_3 - x_4 = -6 \\
x_1 + 2x_2 + 3x_3 - x_4 = -4
\end{cases}
$$

In [58]:
A = np.array([
    [1, 1, 2, 3],
    [3, -1, -1, -2],
    [2, -3, -1, -1],
    [1, 2, 3, -1]
], dtype=float)

B = np.array([1, -4, -6, -4], dtype=float)

def cramer(A, B):
    det_a = np.linalg.det(A)
    if det_a == 0:
        raise ValueError("Визначник A дорівнює нулю. Правило Крамера не можна застосувати.")
    n = len(B)
    x = np.zeros(n)
    for i in range(n):
        a_i = A.copy()
        a_i[:, i] = B
        x[i] = np.linalg.det(a_i) / det_a
    return x

In [59]:
x = cramer(A, B)
print("Розв’язок системи за формулами Крамера:")
print(x)

Розв’язок системи за формулами Крамера:
[-0.55555556  1.88888889 -2.          1.22222222]


In [60]:
check = A @ x
print("Перевірка через матричне множення (Ax):")
print(check)

Перевірка через матричне множення (Ax):
[ 1. -4. -6. -4.]


In [61]:
cramer2 = np.linalg.inv(A) @ B
print("Розв’язок через обернену матрицю:")
print(cramer2)

Розв’язок через обернену матрицю:
[-0.55555556  1.88888889 -2.          1.22222222]


In [62]:
cramer3 = np.linalg.solve(A, B)
print("Розв’язок через numpy.linalg.solve():")
print(cramer3)

Розв’язок через numpy.linalg.solve():
[-0.55555556  1.88888889 -2.          1.22222222]


In [63]:
print("Крамер == обернена:", np.allclose(x, cramer2))
print("Крамер == numpy:", np.allclose(x, cramer3))
print("обернена == numpy:", np.allclose(x, cramer3))

Крамер == обернена: True
Крамер == numpy: True
обернена == numpy: True


### Завдання 3

**Постановка задачі:**

Обчислити значення матричного виразу

2(A + B)(2B - A)

$$
A = \begin{pmatrix}
2 & 3 & -1 \\
4 & 5 & 2 \\
-1 & 0 & 7
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
-1 & 0 & 5 \\
0 & 1 & 3 \\
2 & -2 & 4
\end{pmatrix}
$$

а) з використанням універсальних функцій бібліотеки NumPy  
b) за допомогою ітеративних конструкцій (циклів або спискових включень)  
c) для обох випадків підрахувати час виконання скрипту та зробити висновок.  

Порівняти результати за допомогою `numpy.allclose()`.

In [70]:
A = np.array([[2, 3, -1],
                  [4, 5, 2],
                  [-1, 0, 7]], dtype=float)

B = np.array([[-1, 0, 5],
                  [0, 1, 3],
                  [2, -2, 4]], dtype=float)

start = time.time()
result_numpy = 2 * (A + B) @ (2*B - A)
end = time.time()

print("Результат через NumPy:\n", result_numpy)
print("Час виконання NumPy:", end - start)

Результат через NumPy:
 [[   8.  -56.   54.]
 [ -30. -100.  146.]
 [ 118.  -82.   28.]]
Час виконання NumPy: 0.0003502368927001953


In [71]:
A = [[2, 3, -1], [4, 5, 2], [-1, 0, 7]]
B = [[-1, 0, 5], [0, 1, 3], [2, -2, 4]]

C = []
for i in range(3):
    row = []
    for j in range(3):
        row.append(2 * (A[i][j] + B[i][j]))
    C.append(row)

D = []
for i in range(3):
    row = []
    for j in range(3):
        row.append(2 * B[i][j] - A[i][j])
    D.append(row)

result = []
for i in range(3):
    row = []
    for j in range(3):
        suma = 0
        for k in range(3):
            suma += C[i][k] * D[k][j]
        row.append(suma)
    result.append(row)

print("Результат:")
for row in result:
    print(row)
print("Час виконання:", end - start)

Результат:
[8, -56, 54]
[-30, -100, 146]
[118, -82, 28]
Час виконання: 0.0003502368927001953


In [72]:
print("Порівняння: ", np.allclose(result_numpy, result))

Порівняння:  True
